"""empty message

Revision ID: 43712d7fe0e2
Revises: e4e085c0fbff
Create Date: 2022-11-27 11:07:46.363438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43712d7fe0e2'
down_revision = 'e4e085c0fbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
